// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';

//Employee
export const RECEIVE_EMPLOYEES ='RECEIVE_EMPLOYEES';
export const RECEIVE_EMPLOYEE_BY_ID ='RECEIVE_EMPLOYEE_BY_ID';
export const ERROR_RECEIVE_EMPLOYEES = 'ERROR_RECEIVE_EMPLOYEES';
export const ERROR_RECEIVE_EMPLOYEE_BY_ID ='RECEIVE_EMPLOYEE_BY_ID';
export const DELETED_EMPLOYEE ='DELETE_EMPLOYEE';
export const ERROR_DELETE_EMPLOYEE ='ERROR_DELETE_EMPLOYEE';
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const ERROR_UPDATE_EMPLOYEE = 'ERROR_UPDATE_EMPLOYEE';
export const ERROR_CREATE_EMPLOYEE = 'ERROR_CREATE_EMPLOYEE';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';

//Company
export const RECEIVE_COMPANY ='RECEIVE_COMPANY';
export const ERROR_RECEIVE_COMPANY = 'ERROR_RECEIVE_COMPANY';
